// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/dataModel/{name}": {
            "get": {
                "description": "Returns JSON with 5 tables - Product Hierarchy, Xpath Connections, MetaData, Raw Materials, Data",
                "produces": [
                    "application/json",
                    "text/plain"
                ],
                "tags": [
                    "dataModels"
                ],
                "summary": "Returns data model for Merck DB Modeling Project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name of product",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "json",
                        "description": "output encoding of ('json','csv','csvFile')",
                        "name": "encode",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/version": {
            "get": {
                "description": "Returns information about a given hierarchy element or measurement",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metadata"
                ],
                "summary": "API Version number",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
